apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  labels:
    app: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: rjsdn9025/awsc:latest
        env:
        - name: APP_SERVICE_HOST
          value: "http://a4a6c1d52f32f4c078b477c6b7845f2e-1636800644.ap-northeast-2.elb.amazonaws.com"
        - name: NOTIF_SERVICE_HOST
          value: "http://a4a6c1d52f32f4c078b477c6b7845f2e-1636800644.ap-northeast-2.elb.amazonaws.com"
        - name: DB_NAME
          value: "sbcntrapp"
        - name: DB_HOST
          value: "sbcntr-db.cluster-czk4yeia2fwr.ap-northeast-2.rds.amazonaws.com"  # 실제 DB 호스트 URL로 변경하세요
        - name: DB_USERNAME
          value: "admin"
        - name: DB_PASSWORD
          value: "n6*H2~7dz-Kb4SD-(}JAPUSY7|X9"
        - name: SESSION_SECRET_KEY
          value: "612bc4bdf8f21b2429a26b0de1b28727e1f118b02d7ffb7592557121aa8df497"
        ports:
        - containerPort: 80

